/* eslint-disable @typescript-eslint/camelcase */
const baseImageUrl = 'http://wxbs.oss-cn-hangzhou.aliyuncs.com/wehub/Emoji/'

export const CustomEmojis = [
  {
    name: '微笑',
    short_names: ['001'],
    keywords: ['微笑'],
    imageUrl: baseImageUrl + '001.png',
  },
  {
    name: '撇嘴',
    short_names: ['002'],
    keywords: ['撇嘴'],
    imageUrl: baseImageUrl + '002.png',
  },
  {
    name: '色',
    short_names: ['003'],
    keywords: ['色'],
    imageUrl: baseImageUrl + '003.png',
  },
  {
    name: '发呆',
    short_names: ['004'],
    keywords: ['发呆'],
    imageUrl: baseImageUrl + '004.png',
  },
  {
    name: '得意',
    short_names: ['005'],
    keywords: ['得意'],
    imageUrl: baseImageUrl + '005.png',
  },
  {
    name: '流泪',
    short_names: ['006'],
    keywords: ['流泪'],
    imageUrl: baseImageUrl + '006.png',
  },
  {
    name: '害羞',
    short_names: ['007'],
    keywords: ['害羞'],
    imageUrl: baseImageUrl + '007.png',
  },
  {
    name: '闭嘴',
    short_names: ['008'],
    keywords: ['闭嘴'],
    imageUrl: baseImageUrl + '008.png',
  },
  {
    name: '睡',
    short_names: ['009'],
    keywords: ['睡'],
    imageUrl: baseImageUrl + '009.png',
  },
  {
    name: '大哭',
    short_names: ['010'],
    keywords: ['大哭'],
    imageUrl: baseImageUrl + '010.png',
  },
  {
    name: '尴尬',
    short_names: ['011'],
    keywords: ['尴尬'],
    imageUrl: baseImageUrl + '011.png',
  },
  {
    name: '发怒',
    short_names: ['012'],
    keywords: ['发怒'],
    imageUrl: baseImageUrl + '012.png',
  },
  {
    name: '调皮',
    short_names: ['013'],
    keywords: ['调皮'],
    imageUrl: baseImageUrl + '013.png',
  },
  {
    name: '呲牙',
    short_names: ['014'],
    keywords: ['呲牙'],
    imageUrl: baseImageUrl + '014.png',
  },
  {
    name: '惊讶',
    short_names: ['015'],
    keywords: ['惊讶'],
    imageUrl: baseImageUrl + '015.png',
  },
  {
    name: '难过',
    short_names: ['016'],
    keywords: ['难过'],
    imageUrl: baseImageUrl + '016.png',
  },
  {
    name: '酷',
    short_names: ['017'],
    keywords: ['酷'],
    imageUrl: baseImageUrl + '017.png',
  },
  {
    name: '囧',
    short_names: ['018'],
    keywords: ['囧'],
    imageUrl: baseImageUrl + '018.png',
  },
  {
    name: '抓狂',
    short_names: ['019'],
    keywords: ['抓狂'],
    imageUrl: baseImageUrl + '019.png',
  },
  {
    name: '吐',
    short_names: ['020'],
    keywords: ['吐'],
    imageUrl: baseImageUrl + '020.png',
  },
  {
    name: '偷笑',
    short_names: ['021'],
    keywords: ['偷笑'],
    imageUrl: baseImageUrl + '021.png',
  },
  {
    name: '愉快',
    short_names: ['022'],
    keywords: ['愉快'],
    imageUrl: baseImageUrl + '022.png',
  },
  {
    name: '白眼',
    short_names: ['023'],
    keywords: ['白眼'],
    imageUrl: baseImageUrl + '023.png',
  },
  {
    name: '傲慢',
    short_names: ['024'],
    keywords: ['傲慢'],
    imageUrl: baseImageUrl + '024.png',
  },
  {
    name: '饥饿',
    short_names: ['025'],
    keywords: ['饥饿'],
    imageUrl: baseImageUrl + '025.png',
  },
  {
    name: '困',
    short_names: ['026'],
    keywords: ['困'],
    imageUrl: baseImageUrl + '026.png',
  },
  {
    name: '惊恐',
    short_names: ['027'],
    keywords: ['惊恐'],
    imageUrl: baseImageUrl + '027.png',
  },
  {
    name: '流汗',
    short_names: ['028'],
    keywords: ['流汗'],
    imageUrl: baseImageUrl + '028.png',
  },
  {
    name: '憨笑',
    short_names: ['029'],
    keywords: ['憨笑'],
    imageUrl: baseImageUrl + '029.png',
  },
  {
    name: '悠闲',
    short_names: ['030'],
    keywords: ['悠闲'],
    imageUrl: baseImageUrl + '030.png',
  },
  {
    name: '奋斗',
    short_names: ['031'],
    keywords: ['奋斗'],
    imageUrl: baseImageUrl + '031.png',
  },
  {
    name: '咒骂',
    short_names: ['032'],
    keywords: ['咒骂'],
    imageUrl: baseImageUrl + '032.png',
  },
  {
    name: '疑问',
    short_names: ['033'],
    keywords: ['疑问'],
    imageUrl: baseImageUrl + '033.png',
  },
  {
    name: '嘘',
    short_names: ['034'],
    keywords: ['嘘'],
    imageUrl: baseImageUrl + '034.png',
  },
  {
    name: '晕',
    short_names: ['035'],
    keywords: ['晕'],
    imageUrl: baseImageUrl + '035.png',
  },
  {
    name: '疯了',
    short_names: ['036'],
    keywords: ['疯了'],
    imageUrl: baseImageUrl + '036.png',
  },
  {
    name: '衰',
    short_names: ['037'],
    keywords: ['衰'],
    imageUrl: baseImageUrl + '037.png',
  },
  {
    name: '骷髅',
    short_names: ['038'],
    keywords: ['骷髅'],
    imageUrl: baseImageUrl + '038.png',
  },
  {
    name: '敲打',
    short_names: ['039'],
    keywords: ['敲打'],
    imageUrl: baseImageUrl + '039.png',
  },
  {
    name: '再见',
    short_names: ['040'],
    keywords: ['再见'],
    imageUrl: baseImageUrl + '040.png',
  },
  {
    name: '擦汗',
    short_names: ['041'],
    keywords: ['擦汗'],
    imageUrl: baseImageUrl + '041.png',
  },
  {
    name: '抠鼻',
    short_names: ['042'],
    keywords: ['抠鼻'],
    imageUrl: baseImageUrl + '042.png',
  },
  {
    name: '鼓掌',
    short_names: ['043'],
    keywords: ['鼓掌'],
    imageUrl: baseImageUrl + '043.png',
  },
  {
    name: '糗大了',
    short_names: ['044'],
    keywords: ['糗大了'],
    imageUrl: baseImageUrl + '044.png',
  },
  {
    name: '坏笑',
    short_names: ['045'],
    keywords: ['坏笑'],
    imageUrl: baseImageUrl + '045.png',
  },
  {
    name: '左哼哼',
    short_names: ['046'],
    keywords: ['左哼哼'],
    imageUrl: baseImageUrl + '046.png',
  },
  {
    name: '右哼哼',
    short_names: ['047'],
    keywords: ['右哼哼'],
    imageUrl: baseImageUrl + '047.png',
  },
  {
    name: '哈欠',
    short_names: ['048'],
    keywords: ['哈欠'],
    imageUrl: baseImageUrl + '048.png',
  },
  {
    name: '鄙视',
    short_names: ['049'],
    keywords: ['鄙视'],
    imageUrl: baseImageUrl + '049.png',
  },
  {
    name: '委屈',
    short_names: ['050'],
    keywords: ['委屈'],
    imageUrl: baseImageUrl + '050.png',
  },
  {
    name: '快哭了',
    short_names: ['051'],
    keywords: ['快哭了'],
    imageUrl: baseImageUrl + '051.png',
  },
  {
    name: '阴险',
    short_names: ['052'],
    keywords: ['阴险'],
    imageUrl: baseImageUrl + '052.png',
  },
  {
    name: '亲亲',
    short_names: ['053'],
    keywords: ['亲亲'],
    imageUrl: baseImageUrl + '053.png',
  },
  {
    name: '吓',
    short_names: ['054'],
    keywords: ['吓'],
    imageUrl: baseImageUrl + '054.png',
  },
  {
    name: '可怜',
    short_names: ['055'],
    keywords: ['可怜'],
    imageUrl: baseImageUrl + '055.png',
  },
  {
    name: '菜刀',
    short_names: ['056'],
    keywords: ['菜刀'],
    imageUrl: baseImageUrl + '056.png',
  },
  {
    name: '西瓜',
    short_names: ['057'],
    keywords: ['西瓜'],
    imageUrl: baseImageUrl + '057.png',
  },
  {
    name: '啤酒',
    short_names: ['058'],
    keywords: ['啤酒'],
    imageUrl: baseImageUrl + '058.png',
  },
  {
    name: '篮球',
    short_names: ['059'],
    keywords: ['篮球'],
    imageUrl: baseImageUrl + '059.png',
  },
  {
    name: '乒乓',
    short_names: ['060'],
    keywords: ['乒乓'],
    imageUrl: baseImageUrl + '060.png',
  },
  {
    name: '咖啡',
    short_names: ['061'],
    keywords: ['咖啡'],
    imageUrl: baseImageUrl + '061.png',
  },
  {
    name: '饭',
    short_names: ['062'],
    keywords: ['饭'],
    imageUrl: baseImageUrl + '062.png',
  },
  {
    name: '猪头',
    short_names: ['063'],
    keywords: ['猪头'],
    imageUrl: baseImageUrl + '063.png',
  },
  {
    name: '玫瑰',
    short_names: ['064'],
    keywords: ['玫瑰'],
    imageUrl: baseImageUrl + '064.png',
  },
  {
    name: '凋谢',
    short_names: ['065'],
    keywords: ['凋谢'],
    imageUrl: baseImageUrl + '065.png',
  },
  {
    name: '嘴唇',
    short_names: ['066'],
    keywords: ['嘴唇'],
    imageUrl: baseImageUrl + '066.png',
  },
  {
    name: '爱心',
    short_names: ['067'],
    keywords: ['爱心'],
    imageUrl: baseImageUrl + '067.png',
  },
  {
    name: '心碎',
    short_names: ['068'],
    keywords: ['心碎'],
    imageUrl: baseImageUrl + '068.png',
  },
  {
    name: '蛋糕',
    short_names: ['069'],
    keywords: ['蛋糕'],
    imageUrl: baseImageUrl + '069.png',
  },
  {
    name: '闪电',
    short_names: ['070'],
    keywords: ['闪电'],
    imageUrl: baseImageUrl + '070.png',
  },
  {
    name: '炸弹',
    short_names: ['071'],
    keywords: ['炸弹'],
    imageUrl: baseImageUrl + '071.png',
  },
  {
    name: '刀',
    short_names: ['072'],
    keywords: ['刀'],
    imageUrl: baseImageUrl + '072.png',
  },
  {
    name: '足球',
    short_names: ['073'],
    keywords: ['足球'],
    imageUrl: baseImageUrl + '073.png',
  },
  {
    name: '瓢虫',
    short_names: ['074'],
    keywords: ['瓢虫'],
    imageUrl: baseImageUrl + '074.png',
  },
  {
    name: '便便',
    short_names: ['075'],
    keywords: ['便便'],
    imageUrl: baseImageUrl + '075.png',
  },
  {
    name: '月亮',
    short_names: ['076'],
    keywords: ['月亮'],
    imageUrl: baseImageUrl + '076.png',
  },
  {
    name: '太阳',
    short_names: ['077'],
    keywords: ['太阳'],
    imageUrl: baseImageUrl + '077.png',
  },
  {
    name: '礼物',
    short_names: ['078'],
    keywords: ['礼物'],
    imageUrl: baseImageUrl + '078.png',
  },
  {
    name: '拥抱',
    short_names: ['079'],
    keywords: ['拥抱'],
    imageUrl: baseImageUrl + '079.png',
  },
  {
    name: '强',
    short_names: ['080'],
    keywords: ['强'],
    imageUrl: baseImageUrl + '080.png',
  },
  {
    name: '弱',
    short_names: ['081'],
    keywords: ['弱'],
    imageUrl: baseImageUrl + '081.png',
  },
  {
    name: '握手',
    short_names: ['082'],
    keywords: ['握手'],
    imageUrl: baseImageUrl + '082.png',
  },
  {
    name: '胜利',
    short_names: ['083'],
    keywords: ['胜利'],
    imageUrl: baseImageUrl + '083.png',
  },
  {
    name: '抱拳',
    short_names: ['084'],
    keywords: ['抱拳'],
    imageUrl: baseImageUrl + '084.png',
  },
  {
    name: '勾引',
    short_names: ['085'],
    keywords: ['勾引'],
    imageUrl: baseImageUrl + '085.png',
  },
  {
    name: '拳头',
    short_names: ['086'],
    keywords: ['拳头'],
    imageUrl: baseImageUrl + '086.png',
  },
  {
    name: '差劲',
    short_names: ['087'],
    keywords: ['差劲'],
    imageUrl: baseImageUrl + '087.png',
  },
  {
    name: '爱你',
    short_names: ['088'],
    keywords: ['爱你'],
    imageUrl: baseImageUrl + '088.png',
  },
  {
    name: 'NO',
    short_names: ['089'],
    keywords: ['NO'],
    imageUrl: baseImageUrl + '089.png',
  },
  {
    name: 'OK',
    short_names: ['090'],
    keywords: ['OK'],
    imageUrl: baseImageUrl + '090.png',
  },
  {
    name: '爱情',
    short_names: ['091'],
    keywords: ['爱情'],
    imageUrl: baseImageUrl + '091.png',
  },
  {
    name: '飞吻',
    short_names: ['092'],
    keywords: ['飞吻'],
    imageUrl: baseImageUrl + '092.png',
  },
  {
    name: '跳跳',
    short_names: ['093'],
    keywords: ['跳跳'],
    imageUrl: baseImageUrl + '093.png',
  },
  {
    name: '发抖',
    short_names: ['094'],
    keywords: ['发抖'],
    imageUrl: baseImageUrl + '094.png',
  },
  {
    name: '怄火',
    short_names: ['095'],
    keywords: ['怄火'],
    imageUrl: baseImageUrl + '095.png',
  },
  {
    name: '转圈',
    short_names: ['096'],
    keywords: ['转圈'],
    imageUrl: baseImageUrl + '096.png',
  },
  {
    name: '磕头',
    short_names: ['097'],
    keywords: ['磕头'],
    imageUrl: baseImageUrl + '097.png',
  },
  {
    name: '回头',
    short_names: ['098'],
    keywords: ['回头'],
    imageUrl: baseImageUrl + '098.png',
  },
  {
    name: '跳绳',
    short_names: ['099'],
    keywords: ['跳绳'],
    imageUrl: baseImageUrl + '099.png',
  },
  {
    name: '投降',
    short_names: ['100'],
    keywords: ['投降'],
    imageUrl: baseImageUrl + '100.png',
  },
  {
    name: '激动',
    short_names: ['101'],
    keywords: ['激动'],
    imageUrl: baseImageUrl + '101.png',
  },
  {
    name: '乱舞',
    short_names: ['102'],
    keywords: ['乱舞'],
    imageUrl: baseImageUrl + '102.png',
  },
  {
    name: '献吻',
    short_names: ['103'],
    keywords: ['献吻'],
    imageUrl: baseImageUrl + '103.png',
  },
  {
    name: '左太极',
    short_names: ['104'],
    keywords: ['左太极'],
    imageUrl: baseImageUrl + '104.png',
  },
  {
    name: '右太极',
    short_names: ['105'],
    keywords: ['右太极'],
    imageUrl: baseImageUrl + '105.png',
  },
  {
    name: '嘿哈',
    short_names: ['106'],
    keywords: ['嘿哈'],
    imageUrl: baseImageUrl + '106.png',
  },
  {
    name: '捂脸',
    short_names: ['107'],
    keywords: ['捂脸'],
    imageUrl: baseImageUrl + '107.png',
  },
  {
    name: '奸笑',
    short_names: ['108'],
    keywords: ['奸笑'],
    imageUrl: baseImageUrl + '108.png',
  },
  {
    name: '机智',
    short_names: ['109'],
    keywords: ['机智'],
    imageUrl: baseImageUrl + '109.png',
  },
  {
    name: '皱眉',
    short_names: ['110'],
    keywords: ['皱眉'],
    imageUrl: baseImageUrl + '110.png',
  },
  {
    name: '耶',
    short_names: ['111'],
    keywords: ['耶'],
    imageUrl: baseImageUrl + '111.png',
  },
  {
    name: '红包',
    short_names: ['112'],
    keywords: ['红包'],
    imageUrl: baseImageUrl + '112.png',
  },
  {
    name: '蜡烛',
    short_names: ['113'],
    keywords: ['蜡烛'],
    imageUrl: baseImageUrl + '113.png',
  },
]
