/* eslint-disable @typescript-eslint/camelcase */
const baseImageUrl = 'http://wxbs.oss-cn-hangzhou.aliyuncs.com/wehub/Emoji/'

export const CustomEmojis = [
  {
    name: '微笑',
    short_names: ['001'],
    keywords: ['微笑'],
    imageUrl: baseImageUrl + '001.png',
  },
  {
    name: '撇嘴',
    short_names: ['002'],
    keywords: ['撇嘴'],
    imageUrl: baseImageUrl + '002.png',
  },
  {
    name: '色',
    short_names: ['003'],
    keywords: ['色'],
    imageUrl: baseImageUrl + '003.png',
  },
  {
    name: '发呆',
    short_names: ['004'],
    keywords: ['发呆'],
    imageUrl: baseImageUrl + '004.png',
  },
  {
    name: '得意',
    short_names: ['005'],
    keywords: ['得意'],
    imageUrl: baseImageUrl + '005.png',
  },
  {
    name: '流泪',
    short_names: ['006'],
    keywords: ['流泪'],
    imageUrl: baseImageUrl + '006.png',
  },
  {
    name: '害羞',
    short_names: ['007'],
    keywords: ['害羞'],
    imageUrl: baseImageUrl + '007.png',
  },
  {
    name: '闭嘴',
    short_names: ['008'],
    keywords: ['闭嘴'],
    imageUrl: baseImageUrl + '008.png',
  },
  {
    name: '睡',
    short_names: ['009'],
    keywords: ['睡'],
    imageUrl: baseImageUrl + '009.png',
  },
  {
    name: '大哭',
    short_names: ['010'],
    keywords: ['大哭'],
    imageUrl: baseImageUrl + '010.png',
  },
  {
    name: '尴尬',
    short_names: ['011'],
    keywords: ['尴尬'],
    imageUrl: baseImageUrl + '011.png',
  },
  {
    name: '发怒',
    short_names: ['012'],
    keywords: ['发怒'],
    imageUrl: baseImageUrl + '012.png',
  },
  {
    name: '调皮',
    short_names: ['013'],
    keywords: ['调皮'],
    imageUrl: baseImageUrl + '013.png',
  },
  {
    name: '呲牙',
    short_names: ['014'],
    keywords: ['呲牙'],
    imageUrl: baseImageUrl + '014.png',
  },
  {
    name: '惊讶',
    short_names: ['015'],
    keywords: ['惊讶'],
    imageUrl: baseImageUrl + '015.png',
  },
  {
    name: '难过',
    short_names: ['016'],
    keywords: ['难过'],
    imageUrl: baseImageUrl + '016.png',
  },
  {
    name: '酷',
    short_names: ['017'],
    keywords: ['酷'],
    imageUrl: baseImageUrl + '017.png',
  },
  {
    name: '囧',
    short_names: ['018'],
    keywords: ['囧'],
    imageUrl: baseImageUrl + '018.png',
  },
  {
    name: '抓狂',
    short_names: ['019'],
    keywords: ['抓狂'],
    imageUrl: baseImageUrl + '019.png',
  },
  {
    name: '吐',
    short_names: ['020'],
    keywords: ['吐'],
    imageUrl: baseImageUrl + '020.png',
  },
  {
    name: '偷笑',
    short_names: ['021'],
    keywords: ['偷笑'],
    imageUrl: baseImageUrl + '021.png',
  },
  {
    name: '愉快',
    short_names: ['022'],
    keywords: ['愉快'],
    imageUrl: baseImageUrl + '022.png',
  },
  {
    name: '白眼',
    short_names: ['023'],
    keywords: ['白眼'],
    imageUrl: baseImageUrl + '023.png',
  },
  {
    name: '傲慢',
    short_names: ['024'],
    keywords: ['傲慢'],
    imageUrl: baseImageUrl + '024.png',
  },
  {
    name: '饥饿',
    short_names: ['025'],
    keywords: ['饥饿'],
    imageUrl: baseImageUrl + '025.png',
  },
  {
    name: '困',
    short_names: ['026'],
    keywords: ['困'],
    imageUrl: baseImageUrl + '026.png',
  },
  {
    name: '惊恐',
    short_names: ['027'],
    keywords: ['惊恐'],
    imageUrl: baseImageUrl + '027.png',
  },
  {
    name: '流汗',
    short_names: ['028'],
    keywords: ['流汗'],
    imageUrl: baseImageUrl + '028.png',
  },
  {
    name: '憨笑',
    short_names: ['029'],
    keywords: ['憨笑'],
    imageUrl: baseImageUrl + '029.png',
  },
  {
    name: '悠闲',
    short_names: ['030'],
    keywords: ['悠闲'],
    imageUrl: baseImageUrl + '030.png',
  },
  {
    name: '奋斗',
    short_names: ['031'],
    keywords: ['奋斗'],
    imageUrl: baseImageUrl + '031.png',
  },
  {
    name: '咒骂',
    short_names: ['032'],
    keywords: ['咒骂'],
    imageUrl: baseImageUrl + '032.png',
  },
  {
    name: '疑问',
    short_names: ['033'],
    keywords: ['疑问'],
    imageUrl: baseImageUrl + '033.png',
  },
  {
    name: '嘘',
    short_names: ['034'],
    keywords: ['嘘'],
    imageUrl: baseImageUrl + '034.png',
  },
  {
    name: '晕',
    short_names: ['035'],
    keywords: ['晕'],
    imageUrl: baseImageUrl + '035.png',
  },
  {
    name: '疯了',
    short_names: ['036'],
    keywords: ['疯了'],
    imageUrl: baseImageUrl + '036.png',
  },
  {
    name: '衰',
    short_names: ['037'],
    keywords: ['衰'],
    imageUrl: baseImageUrl + '037.png',
  },
  {
    name: '骷髅',
    short_names: ['038'],
    keywords: ['骷髅'],
    imageUrl: baseImageUrl + '038.png',
  },
  {
    name: '敲打',
    short_names: ['039'],
    keywords: ['敲打'],
    imageUrl: baseImageUrl + '039.png',
  },
  {
    name: '再见',
    short_names: ['040'],
    keywords: ['再见'],
    imageUrl: baseImageUrl + '040.png',
  },
  {
    name: '擦汗',
    short_names: ['041'],
    keywords: ['擦汗'],
    imageUrl: baseImageUrl + '041.png',
  },
  {
    name: '抠鼻',
    short_names: ['042'],
    keywords: ['抠鼻'],
    imageUrl: baseImageUrl + '042.png',
  },
  {
    name: '鼓掌',
    short_names: ['043'],
    keywords: ['鼓掌'],
    imageUrl: baseImageUrl + '043.png',
  },
  {
    name: '糗大了',
    short_names: ['044'],
    keywords: ['糗大了'],
    imageUrl: baseImageUrl + '044.png',
  },
  {
    name: '坏笑',
    short_names: ['045'],
    keywords: ['坏笑'],
    imageUrl: baseImageUrl + '045.png',
  },
  {
    name: '左哼哼',
    short_names: ['046'],
    keywords: ['左哼哼'],
    imageUrl: baseImageUrl + '046.png',
  },
  {
    name: '右哼哼',
    short_names: ['047'],
    keywords: ['右哼哼'],
    imageUrl: baseImageUrl + '047.png',
  },
  {
    name: '哈欠',
    short_names: ['048'],
    keywords: ['哈欠'],
    imageUrl: baseImageUrl + '048.png',
  },
  {
    name: '鄙视',
    short_names: ['049'],
    keywords: ['鄙视'],
    imageUrl: baseImageUrl + '049.png',
  },
  {
    name: '委屈',
    short_names: ['050'],
    keywords: ['委屈'],
    imageUrl: baseImageUrl + '050.png',
  },
  {
    name: '快哭了',
    short_names: ['051'],
    keywords: ['快哭了'],
    imageUrl: baseImageUrl + '051.png',
  },
  {
    name: '阴险',
    short_names: ['052'],
    keywords: ['阴险'],
    imageUrl: baseImageUrl + '052.png',
  },
  {
    name: '亲亲',
    short_names: ['053'],
    keywords: ['亲亲'],
    imageUrl: baseImageUrl + '053.png',
  },
  {
    name: '吓',
    short_names: ['054'],
    keywords: ['吓'],
    imageUrl: baseImageUrl + '054.png',
  },
  {
    name: '可怜',
    short_names: ['055'],
    keywords: ['可怜'],
    imageUrl: baseImageUrl + '055.png',
  },
  {
    name: '菜刀',
    short_names: ['056'],
    keywords: ['菜刀'],
    imageUrl: baseImageUrl + '056.png',
  },
  {
    name: '西瓜',
    short_names: ['057'],
    keywords: ['西瓜'],
    imageUrl: baseImageUrl + '057.png',
  },
  {
    name: '啤酒',
    short_names: ['058'],
    keywords: ['啤酒'],
    imageUrl: baseImageUrl + '058.png',
  },
  {
    name: '篮球',
    short_names: ['059'],
    keywords: ['篮球'],
    imageUrl: baseImageUrl + '059.png',
  },
  {
    name: '乒乓',
    short_names: ['060'],
    keywords: ['乒乓'],
    imageUrl: baseImageUrl + '060.png',
  },
  {
    name: '咖啡',
    short_names: ['061'],
    keywords: ['咖啡'],
    imageUrl: baseImageUrl + '061.png',
  },
  {
    name: '饭',
    short_names: ['062'],
    keywords: ['饭'],
    imageUrl: baseImageUrl + '062.png',
  },
  {
    name: '猪头',
    short_names: ['063'],
    keywords: ['猪头'],
    imageUrl: baseImageUrl + '063.png',
  },
  {
    name: '玫瑰',
    short_names: ['064'],
    keywords: ['玫瑰'],
    imageUrl: baseImageUrl + '064.png',
  },
  {
    name: '凋谢',
    short_names: ['065'],
    keywords: ['凋谢'],
    imageUrl: baseImageUrl + '065.png',
  },
  {
    name: '嘴唇',
    short_names: ['066'],
    keywords: ['嘴唇'],
    imageUrl: baseImageUrl + '066.png',
  },
  {
    name: '爱心',
    short_names: ['067'],
    keywords: ['爱心'],
    imageUrl: baseImageUrl + '067.png',
  },
  {
    name: '心碎',
    short_names: ['068'],
    keywords: ['心碎'],
    imageUrl: baseImageUrl + '068.png',
  },
  {
    name: '蛋糕',
    short_names: ['069'],
    keywords: ['蛋糕'],
    imageUrl: baseImageUrl + '069.png',
  },
  {
    name: '闪电',
    short_names: ['070'],
    keywords: ['闪电'],
    imageUrl: baseImageUrl + '070.png',
  },
  {
    name: '炸弹',
    short_names: ['071'],
    keywords: ['炸弹'],
    imageUrl: baseImageUrl + '071.png',
  },
  {
    name: '刀',
    short_names: ['072'],
    keywords: ['刀'],
    imageUrl: baseImageUrl + '072.png',
  },
  {
    name: '足球',
    short_names: ['073'],
    keywords: ['足球'],
    imageUrl: baseImageUrl + '073.png',
  },
  {
    name: '瓢虫',
    short_names: ['074'],
    keywords: ['瓢虫'],
    imageUrl: baseImageUrl + '074.png',
  },
  {
    name: '便便',
    short_names: ['075'],
    keywords: ['便便'],
    imageUrl: baseImageUrl + '075.png',
  },
  {
    name: '月亮',
    short_names: ['076'],
    keywords: ['月亮'],
    imageUrl: baseImageUrl + '076.png',
  },
  {
    name: '太阳',
    short_names: ['077'],
    keywords: ['太阳'],
    imageUrl: baseImageUrl + '077.png',
  },
  {
    name: '礼物',
    short_names: ['078'],
    keywords: ['礼物'],
    imageUrl: baseImageUrl + '078.png',
  },
  {
    name: '拥抱',
    short_names: ['079'],
    keywords: ['拥抱'],
    imageUrl: baseImageUrl + '079.png',
  },
  {
    name: '强',
    short_names: ['080'],
    keywords: ['强'],
    imageUrl: baseImageUrl + '080.png',
  },
  {
    name: '弱',
    short_names: ['081'],
    keywords: ['弱'],
    imageUrl: baseImageUrl + '081.png',
  },
  {
    name: '握手',
    short_names: ['082'],
    keywords: ['握手'],
    imageUrl: baseImageUrl + '082.png',
  },
  {
    name: '胜利',
    short_names: ['083'],
    keywords: ['胜利'],
    imageUrl: baseImageUrl + '083.png',
  },
  {
    name: '抱拳',
    short_names: ['084'],
    keywords: ['抱拳'],
    imageUrl: baseImageUrl + '084.png',
  },
  {
    name: '勾引',
    short_names: ['085'],
    keywords: ['勾引'],
    imageUrl: baseImageUrl + '085.png',
  },
  {
    name: '拳头',
    short_names: ['086'],
    keywords: ['拳头'],
    imageUrl: baseImageUrl + '086.png',
  },
  {
    name: '差劲',
    short_names: ['087'],
    keywords: ['差劲'],
    imageUrl: baseImageUrl + '087.png',
  },
  {
    name: '爱你',
    short_names: ['088'],
    keywords: ['爱你'],
    imageUrl: baseImageUrl + '088.png',
  },
  {
    name: 'NO',
    short_names: ['089'],
    keywords: ['NO'],
    imageUrl: baseImageUrl + '089.png',
  },
  {
    name: 'OK',
    short_names: ['090'],
    keywords: ['OK'],
    imageUrl: baseImageUrl + '090.png',
  },
  {
    name: '爱情',
    short_names: ['091'],
    keywords: ['爱情'],
    imageUrl: baseImageUrl + '091.png',
  },
  {
    name: '飞吻',
    short_names: ['092'],
    keywords: ['飞吻'],
    imageUrl: baseImageUrl + '092.png',
  },
  {
    name: '跳跳',
    short_names: ['093'],
    keywords: ['跳跳'],
    imageUrl: baseImageUrl + '093.png',
  },
  {
    name: '发抖',
    short_names: ['094'],
    keywords: ['发抖'],
    imageUrl: baseImageUrl + '094.png',
  },
  {
    name: '怄火',
    short_names: ['095'],
    keywords: ['怄火'],
    imageUrl: baseImageUrl + '095.png',
  },
  {
    name: '转圈',
    short_names: ['096'],
    keywords: ['转圈'],
    imageUrl: baseImageUrl + '096.png',
  },
  {
    name: '磕头',
    short_names: ['097'],
    keywords: ['磕头'],
    imageUrl: baseImageUrl + '097.png',
  },
  {
    name: '回头',
    short_names: ['098'],
    keywords: ['回头'],
    imageUrl: baseImageUrl + '098.png',
  },
  {
    name: '跳绳',
    short_names: ['099'],
    keywords: ['跳绳'],
    imageUrl: baseImageUrl + '099.png',
  },
  {
    name: '投降',
    short_names: ['100'],
    keywords: ['投降'],
    imageUrl: baseImageUrl + '100.png',
  },
  {
    name: '激动',
    short_names: ['101'],
    keywords: ['激动'],
    imageUrl: baseImageUrl + '101.png',
  },
  {
    name: '乱舞',
    short_names: ['102'],
    keywords: ['乱舞'],
    imageUrl: baseImageUrl + '102.png',
  },
  {
    name: '献吻',
    short_names: ['103'],
    keywords: ['献吻'],
    imageUrl: baseImageUrl + '103.png',
  },
  {
    name: '左太极',
    short_names: ['104'],
    keywords: ['左太极'],
    imageUrl: baseImageUrl + '104.png',
  },
  {
    name: '右太极',
    short_names: ['105'],
    keywords: ['右太极'],
    imageUrl: baseImageUrl + '105.png',
  },
  {
    name: '嘿哈',
    short_names: ['106'],
    keywords: ['嘿哈'],
    imageUrl: baseImageUrl + '106.png',
  },
  {
    name: '捂脸',
    short_names: ['107'],
    keywords: ['捂脸'],
    imageUrl: baseImageUrl + '107.png',
  },
  {
    name: '奸笑',
    short_names: ['108'],
    keywords: ['奸笑'],
    imageUrl: baseImageUrl + '108.png',
  },
  {
    name: '机智',
    short_names: ['109'],
    keywords: ['机智'],
    imageUrl: baseImageUrl + '109.png',
  },
  {
    name: '皱眉',
    short_names: ['110'],
    keywords: ['皱眉'],
    imageUrl: baseImageUrl + '110.png',
  },
  {
    name: '耶',
    short_names: ['111'],
    keywords: ['耶'],
    imageUrl: baseImageUrl + '111.png',
  },
  {
    name: '红包',
    short_names: ['112'],
    keywords: ['红包'],
    imageUrl: baseImageUrl + '112.png',
  },
  {
    name: '蜡烛',
    short_names: ['113'],
    keywords: ['蜡烛'],
    imageUrl: baseImageUrl + '113.png',
  },
  {
    name: '笑脸',
    short_names: ['114'],
    keywords: ['\\e415'],
    imageUrl: baseImageUrl + '114.png',
  },
  {
    name: '开心',
    short_names: ['115'],
    keywords: ['\\uE056'],
    imageUrl: baseImageUrl + '115.png',
  },
  {
    name: '大笑',
    short_names: ['116'],
    keywords: ['\\uE057'],
    imageUrl: baseImageUrl + '116.png',
  },
  {
    name: '热情',
    short_names: ['117'],
    keywords: ['\\uE414'],
    imageUrl: baseImageUrl + '117.png',
  },
  {
    name: '眨眼',
    short_names: ['118'],
    keywords: ['\\uE405'],
    imageUrl: baseImageUrl + '118.png',
  },
  {
    name: '色',
    short_names: ['119'],
    keywords: ['\\uE106'],
    imageUrl: baseImageUrl + '119.png',
  },
  {
    name: '接吻',
    short_names: ['120'],
    keywords: ['\\uE418'],
    imageUrl: baseImageUrl + '120.png',
  },
  {
    name: '亲吻',
    short_names: ['121'],
    keywords: ['\\uE417'],
    imageUrl: baseImageUrl + '121.png',
  },
  {
    name: '脸红',
    short_names: ['122'],
    keywords: ['\\uE40D'],
    imageUrl: baseImageUrl + '122.png',
  },
  {
    name: '漏齿笑',
    short_names: ['123'],
    keywords: ['\\uE404'],
    imageUrl: baseImageUrl + '123.png',
  },
  {
    name: '满意',
    short_names: ['124'],
    keywords: ['\\uE40A'],
    imageUrl: baseImageUrl + '124.png',
  },
  {
    name: '戏弄',
    short_names: ['125'],
    keywords: ['\\uE105'],
    imageUrl: baseImageUrl + '125.png',
  },
  {
    name: '吐舌',
    short_names: ['126'],
    keywords: ['\\uE409'],
    imageUrl: baseImageUrl + '126.png',
  },
  {
    name: '无语',
    short_names: ['127'],
    keywords: ['\\uE40E'],
    imageUrl: baseImageUrl + '127.png',
  },
  {
    name: '得意',
    short_names: ['128'],
    keywords: ['\\uE402'],
    imageUrl: baseImageUrl + '128.png',
  },
  {
    name: '汗',
    short_names: ['129'],
    keywords: ['\\uE108'],
    imageUrl: baseImageUrl + '129.png',
  },
  {
    name: '失望',
    short_names: ['130'],
    keywords: ['\\uE403'],
    imageUrl: baseImageUrl + '130.png',
  },
  {
    name: '低落',
    short_names: ['131'],
    keywords: ['\\uE058'],
    imageUrl: baseImageUrl + '131.png',
  },
  {
    name: '呸',
    short_names: ['132'],
    keywords: ['\\uE407'],
    imageUrl: baseImageUrl + '132.png',
  },
  {
    name: '焦虑',
    short_names: ['133'],
    keywords: ['\\uE401'],
    imageUrl: baseImageUrl + '133.png',
  },
  {
    name: '担心',
    short_names: ['134'],
    keywords: ['\\uE40F'],
    imageUrl: baseImageUrl + '134.png',
  },
  {
    name: '震惊',
    short_names: ['135'],
    keywords: ['\\uE40B'],
    imageUrl: baseImageUrl + '135.png',
  },
  {
    name: '悔恨',
    short_names: ['136'],
    keywords: ['\\uE406'],
    imageUrl: baseImageUrl + '136.png',
  },
  {
    name: '眼泪',
    short_names: ['137'],
    keywords: ['\\uE413'],
    imageUrl: baseImageUrl + '137.png',
  },
  {
    name: '哭',
    short_names: ['138'],
    keywords: ['\\uE411'],
    imageUrl: baseImageUrl + '138.png',
  },
  {
    name: '破涕为笑',
    short_names: ['139'],
    keywords: ['\\uE412'],
    imageUrl: baseImageUrl + '139.png',
  },
  {
    name: '晕',
    short_names: ['140'],
    keywords: ['\\uE410'],
    imageUrl: baseImageUrl + '140.png',
  },
  {
    name: '恐惧',
    short_names: ['141'],
    keywords: ['\\uE107'],
    imageUrl: baseImageUrl + '141.png',
  },
  {
    name: '心烦',
    short_names: ['142'],
    keywords: ['\\uE059'],
    imageUrl: baseImageUrl + '142.png',
  },
  {
    name: '生气',
    short_names: ['143'],
    keywords: ['\\uE416'],
    imageUrl: baseImageUrl + '143.png',
  },
  {
    name: '睡觉',
    short_names: ['144'],
    keywords: ['\\uE408'],
    imageUrl: baseImageUrl + '144.png',
  },
  {
    name: '生病',
    short_names: ['145'],
    keywords: ['\\uE40C'],
    imageUrl: baseImageUrl + '145.png',
  },
  {
    name: '恶魔',
    short_names: ['146'],
    keywords: ['\\uE11A'],
    imageUrl: baseImageUrl + '146.png',
  },
  {
    name: '外星人',
    short_names: ['147'],
    keywords: ['\\uE10C'],
    imageUrl: baseImageUrl + '147.png',
  },
  {
    name: '心',
    short_names: ['148'],
    keywords: ['\\uE022'],
    imageUrl: baseImageUrl + '148.png',
  },
  {
    name: '心碎',
    short_names: ['149'],
    keywords: ['\\uE023'],
    imageUrl: baseImageUrl + '149.png',
  },
  {
    name: '丘比特',
    short_names: ['150'],
    keywords: ['\\uE329'],
    imageUrl: baseImageUrl + '150.png',
  },
  {
    name: '闪烁',
    short_names: ['151'],
    keywords: ['\\uE32E'],
    imageUrl: baseImageUrl + '151.png',
  },
  {
    name: '星星',
    short_names: ['152'],
    keywords: ['\\uE335'],
    imageUrl: baseImageUrl + '152.png',
  },
  {
    name: '叹号',
    short_names: ['153'],
    keywords: ['\\uE337'],
    imageUrl: baseImageUrl + '153.png',
  },
  {
    name: '问号',
    short_names: ['154'],
    keywords: ['\\uE336'],
    imageUrl: baseImageUrl + '154.png',
  },
  {
    name: '睡着',
    short_names: ['155'],
    keywords: ['\\uE13C'],
    imageUrl: baseImageUrl + '155.png',
  },
  {
    name: '水滴',
    short_names: ['156'],
    keywords: ['\\uE331'],
    imageUrl: baseImageUrl + '156.png',
  },
  {
    name: '音乐',
    short_names: ['157'],
    keywords: ['\\uE03E'],
    imageUrl: baseImageUrl + '157.png',
  },
  {
    name: '火',
    short_names: ['158'],
    keywords: ['\\uE11D'],
    imageUrl: baseImageUrl + '158.png',
  },
  {
    name: '便便',
    short_names: ['159'],
    keywords: ['\\uE05A'],
    imageUrl: baseImageUrl + '159.png',
  },
  {
    name: '强',
    short_names: ['160'],
    keywords: ['\\uE00E'],
    imageUrl: baseImageUrl + '160.png',
  },
  {
    name: '弱',
    short_names: ['161'],
    keywords: ['\\uE421'],
    imageUrl: baseImageUrl + '161.png',
  },
  {
    name: '拳头',
    short_names: ['162'],
    keywords: ['\\uE00D'],
    imageUrl: baseImageUrl + '162.png',
  },
  {
    name: '胜利',
    short_names: ['163'],
    keywords: ['\\uE011'],
    imageUrl: baseImageUrl + '163.png',
  },
  {
    name: '上',
    short_names: ['164'],
    keywords: ['\\uE22E'],
    imageUrl: baseImageUrl + '164.png',
  },
  {
    name: '下',
    short_names: ['165'],
    keywords: ['\\uE22F'],
    imageUrl: baseImageUrl + '165.png',
  },
  {
    name: '右',
    short_names: ['166'],
    keywords: ['\\uE231'],
    imageUrl: baseImageUrl + '166.png',
  },
  {
    name: '左',
    short_names: ['167'],
    keywords: ['\\uE230'],
    imageUrl: baseImageUrl + '167.png',
  },
  {
    name: '第一',
    short_names: ['168'],
    keywords: ['\\uE00F'],
    imageUrl: baseImageUrl + '168.png',
  },
  {
    name: '强壮',
    short_names: ['169'],
    keywords: ['\\uE14C'],
    imageUrl: baseImageUrl + '169.png',
  },
  {
    name: '吻',
    short_names: ['170'],
    keywords: ['\\uE111'],
    imageUrl: baseImageUrl + '170.png',
  },
  {
    name: '热恋',
    short_names: ['171'],
    keywords: ['\\e425'],
    imageUrl: baseImageUrl + '171.png',
  },
  {
    name: '男孩',
    short_names: ['172'],
    keywords: ['\\uE001'],
    imageUrl: baseImageUrl + '172.png',
  },
  {
    name: '女孩',
    short_names: ['173'],
    keywords: ['\\uE002'],
    imageUrl: baseImageUrl + '173.png',
  },
  {
    name: '女士',
    short_names: ['174'],
    keywords: ['\\uE005'],
    imageUrl: baseImageUrl + '174.png',
  },
  {
    name: '男士',
    short_names: ['175'],
    keywords: ['\\uE004'],
    imageUrl: baseImageUrl + '175.png',
  },
  {
    name: '天使',
    short_names: ['176'],
    keywords: ['\\uE04E'],
    imageUrl: baseImageUrl + '176.png',
  },
  {
    name: '骷髅',
    short_names: ['177'],
    keywords: ['\\uE11C'],
    imageUrl: baseImageUrl + '177.png',
  },
  {
    name: '红唇',
    short_names: ['178'],
    keywords: ['\\uE003'],
    imageUrl: baseImageUrl + '178.png',
  },
  {
    name: '太阳',
    short_names: ['179'],
    keywords: ['\\uE04A'],
    imageUrl: baseImageUrl + '179.png',
  },
  {
    name: '下雨',
    short_names: ['180'],
    keywords: ['\\uE04B'],
    imageUrl: baseImageUrl + '180.png',
  },
  {
    name: '多云',
    short_names: ['181'],
    keywords: ['\\uE049'],
    imageUrl: baseImageUrl + '181.png',
  },
  {
    name: '雪人',
    short_names: ['182'],
    keywords: ['\\uE048'],
    imageUrl: baseImageUrl + '182.png',
  },
  {
    name: '月亮',
    short_names: ['183'],
    keywords: ['\\uE04C'],
    imageUrl: baseImageUrl + '183.png',
  },
  {
    name: '闪电',
    short_names: ['184'],
    keywords: ['\\uE13D'],
    imageUrl: baseImageUrl + '184.png',
  },
  {
    name: '海浪',
    short_names: ['185'],
    keywords: ['\\uE43E'],
    imageUrl: baseImageUrl + '185.png',
  },
  {
    name: '猫',
    short_names: ['186'],
    keywords: ['\\uE04F'],
    imageUrl: baseImageUrl + '186.png',
  },
  {
    name: '小狗',
    short_names: ['187'],
    keywords: ['\\uE052'],
    imageUrl: baseImageUrl + '187.png',
  },
  {
    name: '老鼠',
    short_names: ['188'],
    keywords: ['\\uE053'],
    imageUrl: baseImageUrl + '188.png',
  },
  {
    name: '仓鼠',
    short_names: ['189'],
    keywords: ['\\uE524'],
    imageUrl: baseImageUrl + '189.png',
  },
  {
    name: '兔子',
    short_names: ['190'],
    keywords: ['\\uE52C'],
    imageUrl: baseImageUrl + '190.png',
  },
  {
    name: '狗',
    short_names: ['191'],
    keywords: ['\\uE52A'],
    imageUrl: baseImageUrl + '191.png',
  },
  {
    name: '青蛙',
    short_names: ['192'],
    keywords: ['\\uE531'],
    imageUrl: baseImageUrl + '192.png',
  },
  {
    name: '老虎',
    short_names: ['193'],
    keywords: ['\\uE050'],
    imageUrl: baseImageUrl + '193.png',
  },
  {
    name: '考拉',
    short_names: ['194'],
    keywords: ['\\uE527'],
    imageUrl: baseImageUrl + '194.png',
  },
  {
    name: '熊',
    short_names: ['195'],
    keywords: ['\\uE051'],
    imageUrl: baseImageUrl + '195.png',
  },
  {
    name: '猪',
    short_names: ['196'],
    keywords: ['\\uE10B'],
    imageUrl: baseImageUrl + '196.png',
  },
  {
    name: '牛',
    short_names: ['197'],
    keywords: ['\\uE52B'],
    imageUrl: baseImageUrl + '197.png',
  },
  {
    name: '野猪',
    short_names: ['198'],
    keywords: ['\\uE52F'],
    imageUrl: baseImageUrl + '198.png',
  },
  {
    name: '猴子',
    short_names: ['199'],
    keywords: ['\\uE109'],
    imageUrl: baseImageUrl + '199.png',
  },
  {
    name: '马',
    short_names: ['200'],
    keywords: ['\\uE01A'],
    imageUrl: baseImageUrl + '200.png',
  },
  {
    name: '蛇',
    short_names: ['201'],
    keywords: ['\\uE52D'],
    imageUrl: baseImageUrl + '201.png',
  },
  {
    name: '鸽子',
    short_names: ['202'],
    keywords: ['\\uE521'],
    imageUrl: baseImageUrl + '202.png',
  },
  {
    name: '鸡',
    short_names: ['203'],
    keywords: ['\\uE52E'],
    imageUrl: baseImageUrl + '203.png',
  },
  {
    name: '企鹅',
    short_names: ['204'],
    keywords: ['\\uE055'],
    imageUrl: baseImageUrl + '204.png',
  },
  {
    name: '毛虫',
    short_names: ['205'],
    keywords: ['\\uE525'],
    imageUrl: baseImageUrl + '205.png',
  },
  {
    name: '章鱼',
    short_names: ['206'],
    keywords: ['\\uE10A'],
    imageUrl: baseImageUrl + '206.png',
  },
  {
    name: '鱼',
    short_names: ['207'],
    keywords: ['\\uE522'],
    imageUrl: baseImageUrl + '207.png',
  },
  {
    name: '鲸鱼',
    short_names: ['208'],
    keywords: ['\\uE054'],
    imageUrl: baseImageUrl + '208.png',
  },
  {
    name: '海豚',
    short_names: ['209'],
    keywords: ['\\uE520'],
    imageUrl: baseImageUrl + '209.png',
  },
  {
    name: '玫瑰',
    short_names: ['210'],
    keywords: ['\\uE032'],
    imageUrl: baseImageUrl + '210.png',
  },
  {
    name: '花',
    short_names: ['211'],
    keywords: ['\\uE303'],
    imageUrl: baseImageUrl + '211.png',
  },
  {
    name: '棕桐树',
    short_names: ['212'],
    keywords: ['\\uE307'],
    imageUrl: baseImageUrl + '212.png',
  },
  {
    name: '仙人掌',
    short_names: ['213'],
    keywords: ['\\uE308'],
    imageUrl: baseImageUrl + '213.png',
  },
  {
    name: '礼盒',
    short_names: ['214'],
    keywords: ['\\uE437'],
    imageUrl: baseImageUrl + '214.png',
  },
  {
    name: '南瓜灯',
    short_names: ['215'],
    keywords: ['\\uE445'],
    imageUrl: baseImageUrl + '215.png',
  },
  {
    name: '鬼魂',
    short_names: ['216'],
    keywords: ['\\uE11B'],
    imageUrl: baseImageUrl + '216.png',
  },
  {
    name: '圣诞老人',
    short_names: ['217'],
    keywords: ['\\uE448'],
    imageUrl: baseImageUrl + '217.png',
  },
  {
    name: '圣诞树',
    short_names: ['218'],
    keywords: ['\\uE033'],
    imageUrl: baseImageUrl + '218.png',
  },
  {
    name: '礼物',
    short_names: ['219'],
    keywords: ['\\uE112'],
    imageUrl: baseImageUrl + '219.png',
  },
  {
    name: '铃',
    short_names: ['220'],
    keywords: ['\\uE325'],
    imageUrl: baseImageUrl + '220.png',
  },
  {
    name: '庆祝',
    short_names: ['221'],
    keywords: ['\\uE312'],
    imageUrl: baseImageUrl + '221.png',
  },
  {
    name: '气球',
    short_names: ['222'],
    keywords: ['\\uE310'],
    imageUrl: baseImageUrl + '222.png',
  },
  {
    name: '光盘',
    short_names: ['223'],
    keywords: ['\\uE126'],
    imageUrl: baseImageUrl + '223.png',
  },
  {
    name: '相机',
    short_names: ['224'],
    keywords: ['\\uE008'],
    imageUrl: baseImageUrl + '224.png',
  },
  {
    name: '录像机',
    short_names: ['225'],
    keywords: ['\\uE03D'],
    imageUrl: baseImageUrl + '225.png',
  },
  {
    name: '电脑',
    short_names: ['226'],
    keywords: ['\\uE00C'],
    imageUrl: baseImageUrl + '226.png',
  },
  {
    name: '电视',
    short_names: ['227'],
    keywords: ['\\uE12A'],
    imageUrl: baseImageUrl + '227.png',
  },
  {
    name: '电话',
    short_names: ['228'],
    keywords: ['\\uE009'],
    imageUrl: baseImageUrl + '228.png',
  },
  {
    name: '解锁',
    short_names: ['229'],
    keywords: ['\\uE145'],
    imageUrl: baseImageUrl + '229.png',
  },
  {
    name: '锁',
    short_names: ['230'],
    keywords: ['\\uE144'],
    imageUrl: baseImageUrl + '230.png',
  },
  {
    name: '钥匙',
    short_names: ['231'],
    keywords: ['\\uE03F'],
    imageUrl: baseImageUrl + '231.png',
  },
  {
    name: '成交',
    short_names: ['232'],
    keywords: ['\\uE03F'],
    imageUrl: baseImageUrl + '232.png',
  },
  {
    name: '灯泡',
    short_names: ['233'],
    keywords: ['\\uE10F'],
    imageUrl: baseImageUrl + '233.png',
  },
  {
    name: '邮箱',
    short_names: ['234'],
    keywords: ['\\uE101'],
    imageUrl: baseImageUrl + '234.png',
  },
  {
    name: '浴缸',
    short_names: ['235'],
    keywords: ['\\uE13F'],
    imageUrl: baseImageUrl + '235.png',
  },
  {
    name: '钱',
    short_names: ['236'],
    keywords: ['\\uE12F'],
    imageUrl: baseImageUrl + '236.png',
  },
  {
    name: '炸弹',
    short_names: ['237'],
    keywords: ['\\uE311'],
    imageUrl: baseImageUrl + '237.png',
  },
  {
    name: '手枪',
    short_names: ['238'],
    keywords: ['\\uE113'],
    imageUrl: baseImageUrl + '238.png',
  },
  {
    name: '药丸',
    short_names: ['239'],
    keywords: ['\\uE30F'],
    imageUrl: baseImageUrl + '239.png',
  },
  {
    name: '橄榄球',
    short_names: ['240'],
    keywords: ['\\uE42B'],
    imageUrl: baseImageUrl + '240.png',
  },
  {
    name: '篮球',
    short_names: ['241'],
    keywords: ['\\uE42A'],
    imageUrl: baseImageUrl + '241.png',
  },
  {
    name: '足球',
    short_names: ['242'],
    keywords: ['\\uE018'],
    imageUrl: baseImageUrl + '242.png',
  },
  {
    name: '棒球',
    short_names: ['243'],
    keywords: ['\\uE016'],
    imageUrl: baseImageUrl + '243.png',
  },
  {
    name: '高尔夫',
    short_names: ['244'],
    keywords: ['\\uE014'],
    imageUrl: baseImageUrl + '244.png',
  },
  {
    name: '奖杯',
    short_names: ['245'],
    keywords: ['\\uE131'],
    imageUrl: baseImageUrl + '245.png',
  },
  {
    name: '入侵者',
    short_names: ['246'],
    keywords: ['\\uE12B'],
    imageUrl: baseImageUrl + '246.png',
  },
  {
    name: '唱歌',
    short_names: ['247'],
    keywords: ['\\uE03C'],
    imageUrl: baseImageUrl + '247.png',
  },
  {
    name: '吉他',
    short_names: ['248'],
    keywords: ['\\uE041'],
    imageUrl: baseImageUrl + '248.png',
  },
  {
    name: '比基尼',
    short_names: ['249'],
    keywords: ['\\uE322'],
    imageUrl: baseImageUrl + '249.png',
  },
  {
    name: '皇冠',
    short_names: ['250'],
    keywords: ['\\uE10E'],
    imageUrl: baseImageUrl + '250.png',
  },
  {
    name: '雨伞',
    short_names: ['251'],
    keywords: ['\\uE43C'],
    imageUrl: baseImageUrl + '251.png',
  },
  {
    name: '手提包',
    short_names: ['252'],
    keywords: ['\\uE323'],
    imageUrl: baseImageUrl + '252.png',
  },
  {
    name: '口红',
    short_names: ['253'],
    keywords: ['\\uE31C'],
    imageUrl: baseImageUrl + '253.png',
  },
  {
    name: '戒指',
    short_names: ['254'],
    keywords: ['\\uE034'],
    imageUrl: baseImageUrl + '254.png',
  },
  {
    name: '钻石',
    short_names: ['255'],
    keywords: ['\\uE035'],
    imageUrl: baseImageUrl + '255.png',
  },
  {
    name: '咖啡',
    short_names: ['256'],
    keywords: ['\\uE045'],
    imageUrl: baseImageUrl + '256.png',
  },
  {
    name: '啤酒',
    short_names: ['257'],
    keywords: ['\\uE047'],
    imageUrl: baseImageUrl + '257.png',
  },
  {
    name: '干杯',
    short_names: ['258'],
    keywords: ['\\uE30C'],
    imageUrl: baseImageUrl + '258.png',
  },
  {
    name: '鸡尾酒',
    short_names: ['259'],
    keywords: ['\\uE044'],
    imageUrl: baseImageUrl + '259.png',
  },
  {
    name: '汉堡',
    short_names: ['260'],
    keywords: ['\\uE120'],
    imageUrl: baseImageUrl + '260.png',
  },
  {
    name: '薯条',
    short_names: ['261'],
    keywords: ['\\uE33B'],
    imageUrl: baseImageUrl + '261.png',
  },
  {
    name: '意面',
    short_names: ['262'],
    keywords: ['\\uE33F'],
    imageUrl: baseImageUrl + '262.png',
  },
  {
    name: '寿司',
    short_names: ['263'],
    keywords: ['\\uE344'],
    imageUrl: baseImageUrl + '263.png',
  },
  {
    name: '面条',
    short_names: ['264'],
    keywords: ['\\uE340'],
    imageUrl: baseImageUrl + '264.png',
  },
  {
    name: '煎蛋',
    short_names: ['265'],
    keywords: ['\\uE147'],
    imageUrl: baseImageUrl + '265.png',
  },
  {
    name: '冰激凌',
    short_names: ['266'],
    keywords: ['\\uE33A'],
    imageUrl: baseImageUrl + '266.png',
  },
  {
    name: '蛋糕',
    short_names: ['267'],
    keywords: ['\\uE34B'],
    imageUrl: baseImageUrl + '267.png',
  },
  {
    name: '苹果',
    short_names: ['268'],
    keywords: ['\\uE345'],
    imageUrl: baseImageUrl + '268.png',
  },
  {
    name: '飞机',
    short_names: ['269'],
    keywords: ['\\uE01D'],
    imageUrl: baseImageUrl + '269.png',
  },
  {
    name: '火箭',
    short_names: ['270'],
    keywords: ['\\uE10D'],
    imageUrl: baseImageUrl + '270.png',
  },
  {
    name: '自行车',
    short_names: ['271'],
    keywords: ['\\uE136'],
    imageUrl: baseImageUrl + '271.png',
  },
  {
    name: '高铁',
    short_names: ['272'],
    keywords: ['\\uE435'],
    imageUrl: baseImageUrl + '272.png',
  },
  {
    name: '警告',
    short_names: ['273'],
    keywords: ['\\uE252'],
    imageUrl: baseImageUrl + '273.png',
  },
  {
    name: '旗',
    short_names: ['274'],
    keywords: ['\\uE132'],
    imageUrl: baseImageUrl + '274.png',
  },
  {
    name: '男人',
    short_names: ['275'],
    keywords: ['\\uE138'],
    imageUrl: baseImageUrl + '275.png',
  },
  {
    name: '女人',
    short_names: ['276'],
    keywords: ['\\uE139'],
    imageUrl: baseImageUrl + '276.png',
  },
  {
    name: '的',
    short_names: ['277'],
    keywords: ['\\uE332'],
    imageUrl: baseImageUrl + '277.png',
  },
  {
    name: 'X',
    short_names: ['278'],
    keywords: ['\\uE333'],
    imageUrl: baseImageUrl + '278.png',
  },
  {
    name: '版权',
    short_names: ['279'],
    keywords: ['\\uE24E'],
    imageUrl: baseImageUrl + '279.png',
  },
  {
    name: '注册商标',
    short_names: ['280'],
    keywords: ['\\uE24F'],
    imageUrl: baseImageUrl + '280.png',
  },
  {
    name: '商标',
    short_names: ['281'],
    keywords: ['\\uE537'],
    imageUrl: baseImageUrl + '281.png',
  },
]
